# Generated by Django 3.0.3 on 2020-02-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='Username',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
