# Generated by Django 3.0.3 on 2020-02-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0002_candidat_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='Nom',
            new_name='NomPrenom',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='Prenom',
        ),
    ]
