# Generated by Django 3.0.3 on 2020-02-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0003_auto_20200226_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruteur',
            old_name='Nom',
            new_name='NomPrenom',
        ),
        migrations.RemoveField(
            model_name='recruteur',
            name='Prenom',
        ),
    ]
