# Generated by Django 3.0.3 on 2020-02-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0004_auto_20200226_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='cv',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
