# Generated by Django 3.0.3 on 2020-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0005_auto_20200226_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreemploi',
            name='DateI',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='Domaine',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='Offre',
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='Email',
            field=models.EmailField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='EntDescription',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='Location',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='NomEntreprise',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='PostDescription',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='Region',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='Title',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='VilleEntreprise',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='siteweb',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
